[package]
name = "rasterize"
version = "0.1.0"
authors = ["Pavel Aslanov <asl.pavel@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
png = "0.16.4"

[dev-dependencies]
env_logger = "0.7.1"
criterion = "0.3"

[[bench]]
name = "rasterize_bench"
harness = false