[package]
name = "surf_n_term"
version = "0.1.0"
authors = ["Pavel Aslanov <asl.pavel@gmail.com>"]
edition = "2018"

[dependencies]
surface = { path = "surface" }
nix = "0.17.0"
libc = "0.2.69"
signal-hook = "0.1.14"
lazy_static = "1.4.0"
miniz_oxide = "0.3.6"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "decoder"
harness = false
