[package]
authors = ["Pavel Aslanov <asl.pavel@gmail.com>"]
description = "Posix terminal rendering library"
edition = "2018"
homepage = "https://github.com/aslpavel/surf-n-term"
include = [
  "**/*.rs",
  "**/Cargo.toml",
  "**/README.md",
]
license = "MIT"
name = "surf_n_term"
readme = "README.md"
repository = "https://github.com/aslpavel/surf-n-term.git"
version = "0.1.4"

[dependencies]
flate2 = "1.0"
fnv = "1.0"
lazy_static = "1.1"
libc = "0.2"
lru = {version = "0.6", default-features = false}
nix = "0.18"
png = "0.16"
signal-hook = "0.3"
rasterize = "0.1"
# ruster = { path = "../rasterize" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
harness = false
name = "decoder"

[[bench]]
harness = false
name = "quantize"
