[package]
name = "surf_n_term"
version = "0.1.0"
authors = ["Pavel Aslanov <asl.pavel@gmail.com>"]
edition = "2018"

[dependencies]
surface = { path = "surface" }
rasterize = { path = "rasterize" }
nix = "0.18"
libc = "0.2"
fnv = "1.0"
signal-hook = "0.1"
lazy_static = "1.1"
flate2 = "1.0"

[dev-dependencies]
criterion = "0.3.*"

[[bench]]
name = "decoder"
harness = false

[[bench]]
name = "quantize"
harness = false
