[package]
authors = ["Pavel Aslanov <asl.pavel@gmail.com>"]
description = "Posix terminal rendering library"
edition = "2021"
homepage = "https://github.com/aslpavel/surf-n-term"
include = ["**/*.rs", "**/Cargo.toml", "**/README.md"]
license = "MIT"
name = "surf_n_term"
readme = "README.md"
repository = "https://github.com/aslpavel/surf-n-term.git"
version = "0.11.9"

[dependencies]
fnv = "^1.0"
lazy_static = "^1.1"
libc = "^0.2"
lru = { version = "^0.12", default-features = false }
nix = { version = "^0.27", default-features = false, features = [
  "fs",
  "poll",
  "term",
] }
png = "^0.17"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
signal-hook = "^0.3"
tracing = "^0.1"
unicode-width = "^0.1"
either = "^1.9"

rasterize = "^0.3.7"
# rasterize = { path = "../rasterize" }

[dev-dependencies]
criterion = { version = "^0.5", features = ["html_reports"] }

[[bench]]
harness = false
name = "decoder"

[[bench]]
harness = false
name = "quantize"
