[package]
name = "tty-surface"
version = "0.1.0"
authors = ["Pavel Aslanov <asl.pavel@gmail.com>"]
edition = "2018"

[dependencies]
nix = "0.17.0"
libc = "0.2.69"
signal-hook = "0.1.14"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "decoder"
harness = false
