[package]
authors = ["Pavel Aslanov <asl.pavel@gmail.com>"]
edition = "2018"
name = "rasterize"
version = "0.1.0"

[features]
default = []

[dependencies]
log = "0.4.11"
png = {version = "0.16", optional = true}
surface = {path = "../surface"}

[dev-dependencies]
criterion = "0.3"
env_logger = "0.7"

[[bench]]
harness = false
name = "rasterize_bench"
